### ISSUE TITLE
Finalizing DeconvExplorer

### ISSUE THREAD

**Issue by FFinotello** [omnideconv/DeconvExplorer#44]
Hello everyone!

I have opened this issue to collect some ideas on how to improve and finalize DeconvExplorer, as @federicomarini will use his magic hands to make it shine even more :)
Ideally, we would need your feedback by Thursday next week. 

Thanks in advance! 
@mlist @grst @LorenzoMerotto @alex-d13 @constantin-zackl 

PS: We should also make a decision on the final name: `DeconvExplorer` (current) or `deconvexplorer` (aligned to `omnideconv` and `immunedeconv`).

**Comment by alex-d13** [comment]
Closing, points are collected somewhere else.
