### ISSUE TITLE
JS Errors when page is loaded

### ISSUE THREAD

**Issue by PelzKo** [omnideconv/deconvExplorer#61]
- Uncaught ReferenceError: shinyBS is not defined
- downloadable font: download failed (font-family: "Font Awesome 5 Free" style:normal weight:900 stretch:100 src index:1): status=2147746065 source: https://exbio.wzw.tum.de/deconvexplorer/webfonts/fa-solid-900.ttf 
- Uncaught SyntaxError: missing } after property list note: { opened at line 1880, column 123
- The resource from “https://exbio.wzw.tum.de/deconvexplorer/sbs/shinyBS.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

**Comment by alex-d13** [comment]
This should have been fixed by @federicomarini in #59 with ed1e6475f889bfbd7a2b099f33c1075dd4d7f2ae
