### ISSUE TITLE
Clustered Signature does not work with signatures from unit test

### ISSUE THREAD

**Issue by PelzKo** [omnideconv/deconvExplorer#64]
When uploading the signatures from the unit tests (omnideconv/tests/testthat/test_models or omnideconv/tests/testthat/test_results) it does not cluster anything. This could also be due to the data, but that could be checked manually with one example

**Comment by alex-d13** [comment]
The implementation is correct. I just looks for genes with a z-score > 1.5 for each cell type and then puts those next to each other. All remaining genes are placed at the end of the heatmap.

I will add the option to cluster genes hierarchically or just sort the alphabetically.
